### ISSUE TITLE
Improve aliasing

### ISSUE THREAD

**Issue by stvnrlly** [DCgov/groupthink#14]
Since the top-level command installed for each bundle uses its own name to find the scripts in the `~/.orgwide` folder, using an alias makes it unable to find the scripts. Here are some possible solutions:

- Use `~/.orgwide/config.json` to store aliases. This is pretty simple, but might make things slower.
- Remove the alias feature from the user side and move it to the bundle maintainer side. If a bundle has a `setup.json` file with `alias: whatever` set, the command is installed as `whatever`.
- Install all scripts to `/usr/local/bin` rather than keeping them in the repo. They can then all be named with the alias, but updating properly probably still requires storing the alias as in the first option.
- Name the clone of the git repo with the alias. Very simple, but it would allow the same bundle to be accidentally installed under different names.

My preferred approach would be the second—moving it to the bundle metadata—followed by renaming the repos, but I am open to ideas.

**Comment by emanuelfeld** [comment]
Alias is the actual organization on GitHub, so running `groupthink --install blah --alias dcgov` installs the top level command as `blah` in `/usr/local/bin` and the repo as `blah-cli` in `~/.groupthink`. The actual organization name on github is reflected in the repo's remote repository, so running update or upgrade works without doing anything to store the alias.
